version: '3.8'
services: 
  dotnet-app:
    image: mcr.microsoft.com/dotnet/sdk:7.0    
    volumes:
      - .:/app
      - main:/app/main
    working_dir: /app
    ports:
      - 2000:2000
    command: ["dotnet", "run", "--project", "school.csproj", "--urls=http://0.0.0.0:2000"]
    
volumes:
  main: